### ISSUE TITLE
Persistent Heads does not work when heads are placed on a wall

### ISSUE THREAD

**Issue by Cirom** [MC-Machinations/VanillaTweaks#10]
Simply put, when placing a Player Head on a **wall** and breaking it, its name/lore gets reset and it just becomes a "Player Head". When placing it on the **floor**, the name/lore is retained as normal.

Running VanillaTweaks v0.1.12

**Comment by Prof-Bloodstone** [comment]
Hey!

Thanks for the report. I'm gonna be honest, I knew that there's 2 different head blocks, but for some reason I only tested them on the ground. I bet the issue is https://github.com/MC-Machinations/VanillaTweaks/blob/master/src/main/java/me/machinemaker/vanillatweaks/persistentheads/PersistentHeads.java#L60
Just need to add check if it's PLAYER_HEAD or WALL_PLAYER_HEAD or something like that.

I'll take a look at it after work.

**Comment by Prof-Bloodstone** [comment]
Hey @Cirom - got busy with other stuff. I've fixed this - see #11 . There is attached compiled plugin if you'd want to test it, but I'm sure Jake will merge it soon :)

**Comment by Titaniumtown** [comment]
I thought this is vanilla behavior, title and lore not persisting when placed and broken. Purpur has a patch that makes title and lore persist when a head is placed and broken.

**Comment by Prof-Bloodstone** [comment]
@Titaniumtown yes, this is Vanilla behavior. But I added it as a module to VanillaTweaks which provides similar behavior to what Purpurs patch does - not everyone wants to run Purpur.
